---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  TeamName:
    Type: String

Resources:

  LambdaWriteChatRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "ApiGatewayLogsPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:PutItem"
                Resource: "*"

  LambdaWriteChat:
    Type: AWS::Lambda::Function
    Properties:
      Description: "A chat write function"
      FunctionName: !Sub "chat-write-${TeamName}"
      Handler: "index.handler"
      Role:
        Fn::GetAtt: [LambdaWriteChatRole, "Arn"]
      Runtime: "nodejs6.10"
      MemorySize: "128"
      Timeout: "2"
      Code:
        "ZipFile": !Sub >
          var AWS = require('aws-sdk');
          var dynamodb = new AWS.DynamoDB({apiVersion: '2012-08-10'});

          exports.handler = (event, context, callback) => {
            console.log('Event:', JSON.stringify(event));
            console.log("try to save message");

            var timestamp = new Date().getTime().toString();
            dynamodb.putItem({
                "TableName": "${TeamName}-chat",
                "Item" : {
                    "timestamp": {"N": timestamp },
                    "username": {"S": event.username },
                    "message": {"S": event.message}
                }
            }, function(err, data) {
                if (err) {
                    console.log(JSON.stringify(err));
                    callback('putting item failed: ' + err);
                }
                else {
                    console.log('success: ' + JSON.stringify(data));
                }
            });
          };

Outputs:

  LambdaWriteChatArn:
    Export:
      Name: !Sub "${AWS::StackName}-LambdaWriteChatArn"
    Value:
      Fn::GetAtt: [LambdaWriteChat, "Arn"]
