---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VPCStackName:
    Type: String
  TeamName:
    Type: String
  ImageId:
    Type: String
  KeyName:
    Type: String

Resources:

  ###### EC2 instance ######

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow access via http"
      VpcId: !ImportValue {"Fn::Sub": "${VPCStackName}-vpc-id"}
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: "172.16.0.0/16"
      Tags:
        - Key: Name
          Value: !Sub "${TeamName}-yocto"

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ECRpull
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - ecr:BatchCheckLayerAvailability
                - ecr:BatchGetImage
                - ecr:GetDownloadUrlForLayer
                - ecr:GetAuthorizationToken
              Resource:
                - "*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref Role

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      Comment: "Installs docker as service"
      AWS::CloudFormation::Init:
        configSets:
            default:
              - docker
        docker:
          packages:
            yum:
              docker: []
          services:
            sysvinit:
              docker:
                enabled: true
                ensureRunning: true
    Properties:
      ImageId: !Ref ImageId
      InstanceType: "t2.nano"
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: !Ref KeyName
      UserData:
        "Fn::Base64": !Sub
          |
            #!/bin/bash -xe

            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchConfiguration --region ${AWS::Region}
            docker run -dp 8080:8080 felixb/yocto-httpd

            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
      SecurityGroups:
        - !Ref SecurityGroup

  ###### ELB ######

  SecurityGroupELB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow access via http"
      VpcId: !ImportValue {"Fn::Sub": "${VPCStackName}-vpc-id"}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: !Sub "${TeamName}-yocto-elb"

  YoctoElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      LoadBalancerName: !Sub "${TeamName}-yocto-elb"
      Subnets:
        - !ImportValue {"Fn::Sub": "${VPCStackName}-subnet-1-public-id"}
        - !ImportValue {"Fn::Sub": "${VPCStackName}-subnet-2-public-id"}
        - !ImportValue {"Fn::Sub": "${VPCStackName}-subnet-3-public-id"}
      SecurityGroups:
        - !Ref SecurityGroupELB
      CrossZone: true
      Listeners:
      - LoadBalancerPort: "80"
        InstancePort: "8080"
        Protocol: HTTP
      HealthCheck:
        Target: HTTP:8080/status
        HealthyThreshold: "2"
        UnhealthyThreshold: "2"
        Interval: "5"
        Timeout: "2"

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: "DNS name"
      HostedZoneId: !ImportValue {"Fn::Sub": "${VPCStackName}-hosted-zone-id"}
      Name: !Join [ "", [ "yocto.", !ImportValue {"Fn::Sub": "${VPCStackName}-hosted-zone-name"} ] ]
      Type: "A"
      AliasTarget:
        HostedZoneId: !GetAtt YoctoElasticLoadBalancer.CanonicalHostedZoneNameID
        DNSName: !GetAtt YoctoElasticLoadBalancer.DNSName

  ###### auto scaling group ######

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: "1"
        MaxBatchSize: "1"
        PauseTime: PT1M
        WaitOnResourceSignals: true
    DependsOn:
      - YoctoElasticLoadBalancer
    Properties:
      LoadBalancerNames:
        - !Sub "${TeamName}-yocto-elb"
      VPCZoneIdentifier:
      - !ImportValue {"Fn::Sub": "${VPCStackName}-subnet-1-public-id"}
      - !ImportValue {"Fn::Sub": "${VPCStackName}-subnet-2-public-id"}
      - !ImportValue {"Fn::Sub": "${VPCStackName}-subnet-3-public-id"}
      LaunchConfigurationName: !Ref LaunchConfiguration
      HealthCheckType: "ELB"
      HealthCheckGracePeriod: "120"
      MinSize: "1"
      DesiredCapacity: "1"
      MaxSize: "2"
      Tags:
        - Key: Name
          Value: !Sub "${TeamName}-yocto"
          PropagateAtLaunch: true

  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: "ChangeInCapacity"
      AutoScalingGroupName: !Ref AutoScalingGroup
      Cooldown: "180"
      ScalingAdjustment: "1"

  ScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: "ChangeInCapacity"
      AutoScalingGroupName: !Ref AutoScalingGroup
      Cooldown: "180"
      ScalingAdjustment: "-1"

  AlarmRequestCountHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TeamName}-Yocto request count too high"
      EvaluationPeriods: "1"
      Statistic: "Sum"
      Threshold: "100"
      Period: "60"
      AlarmActions:
      - Ref: ScaleUpPolicy
      Namespace: "AWS/ELB"
      Dimensions:
      - Name: LoadBalancerName
        Value: !Sub "${TeamName}-yocto-elb"
      ComparisonOperator: "GreaterThanThreshold"
      MetricName: "RequestCount"

  AlarmRequestCountLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TeamName}-Yocto request count too low"
      EvaluationPeriods: "1"
      Statistic: "Sum"
      Threshold: "5"
      Period: "60"
      AlarmActions:
      - Ref: ScaleDownPolicy
      Namespace: "AWS/ELB"
      Dimensions:
      - Name: LoadBalancerName
        Value: !Sub "${TeamName}-yocto-elb"
      ComparisonOperator: "LessThanThreshold"
      MetricName: "RequestCount"
